# Generated by Django 4.2.4 on 2023-10-07 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('detail', models.CharField(max_length=1000)),
                ('cat', models.IntegerField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
