# Generated by Django 4.2.4 on 2023-11-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_student_alter_blog_cat_alter_blog_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='uid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
